import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { BehaviorSubject, Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class UserAuthServiceService {
  private readonly USER_KEY = 'currentUser';
  private jwtDecode: BehaviorSubject<object> = new BehaviorSubject<object>({
    user: {
      iss: 'https://qa-mios.groupcos.com/api/auth/login',
      iat: 1713881724,
      exp: 1713924924,
      nbf: 1713881724,
      jti: 'TJrPXvYJ5CQVwDQ6',
      sub: 75058,
      prv: '23bd5c8949f600adb39e701c400872db7a5976f7',
      idCiu: 75058,
      rrhh_id: 20805,
      roles: [
        'nomina::admin-nomina',
        'rrhh::colaborador',
        'juridica::trabajador',
        'reservas::solicitante',
        'crm::admin',
        'crm::admin',
        'crm::PQR-Encuesta',
        'pqrs::radicador',
        'crm2::admin',
        'crm2::supervisor_crm',
        'ciu::Adminciu',
        'pqrs_soul::admin_externas',
        'encuestas::admin',
        'gestionador-correos::administrador',
        'chat-interno::administrador',
      ],
      rolesId: {
        nomina: [86],
        rrhh: [29],
        juridica: [87],
        reservas: [132],
        crm: [10, 79, 331],
        pqrs: [16],
        crm2: [356, 357],
        ciu: [8],
        pqrs_soul: [483],
        encuestas: [466],
        'gestionador-correos': [373],
      },
      permissions: {
        crm: {
          forms: {
            view: 2,
            edit: 3,
            change: 4,
            save: 1,
            ViewDisabled: 5,
          },
          typify_form_record: {
            view: 2,
            edit: 3,
            save: 1,
            change: 4,
            ViewDisabled: 5,
          },
          escalations: {
            view: 2,
            edit: 3,
            save: 1,
            change: 4,
            ViewDisabled: 5,
          },
          campaigns: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          groups: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          download_report_forms: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          template: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          Tray: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          report: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          dataBase: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          vicidial: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          notificaciones: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          database_manager: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
        },
        crm2: {
          campaigns: {
            save: 1,
            view: 2,
            edit: 3,
            ViewDisabled: 5,
            change: 4,
          },
          groups: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          typify_form_record: {
            ViewDisabled: 5,
            change: 4,
            edit: 3,
            view: 2,
            save: 1,
          },
          forms: {
            ViewDisabled: 5,
            change: 4,
            edit: 3,
            view: 2,
            save: 1,
          },
          download_report_forms: {
            ViewDisabled: 5,
            change: 4,
            edit: 3,
            view: 2,
            save: 1,
          },
          escalations: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          template: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          Tray: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          report: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          dataBase: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          vicidial: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          notificaciones: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
          database_manager: {
            save: 1,
            view: 2,
            edit: 3,
            change: 4,
            ViewDisabled: 5,
          },
        },
      },
      rrhh: {
        name: 'EDWIN SANCHEZ',
        campaign_id: 1,
        ID_number: '1032443628',
        email: 'E.DAVID.SANCHEZ.B@GMAIL.COM',
        phone: '3208803093',
        mobile_phone: null,
        campaign: 'DESARROLLO',
        position: 'SENIOR BACKEND DEVELOPER',
        position_category: 'Administrativa',
        company_id: 1,
        company: 'MONTECHELO INVERSIONES S.A.S',
      },
      applications: [
        {
          id: 6,
          name: 'Nómina',
          key: 'nomina',
          url: '/mios/nomina',
          enforce_schedule: 0,
          show_menu: 1,
          menu: [
            {
              id: 14,
              created_at: null,
              updated_at: '2021-09-19T21:10:38.000000Z',
              application_id: 6,
              name: 'Campañas',
              name_en: null,
              icon: 'fi-rr-pulse',
              url: 'nomina/campaigns',
              index: 1,
            },
            {
              id: 15,
              created_at: null,
              updated_at: '2021-09-19T21:10:38.000000Z',
              application_id: 6,
              name: 'Mis Novedades',
              name_en: null,
              icon: 'fi-rr-calendar',
              url: 'nomina/novelties',
              index: 2,
            },
            {
              id: 18,
              created_at: '2021-07-15T12:18:16.000000Z',
              updated_at: '2022-03-09T15:04:17.000000Z',
              application_id: 6,
              name: 'Liquidaciones',
              name_en: null,
              icon: 'fi-rr-file-check',
              url: 'nomina/liquidations',
              index: 3,
            },
            {
              id: 19,
              created_at: '2021-07-15T12:18:55.000000Z',
              updated_at: '2022-03-09T15:03:45.000000Z',
              application_id: 6,
              name: 'Gestión de Novedades',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'nomina/noveltieslist',
              index: 3,
            },
            {
              id: 20,
              created_at: '2021-07-15T12:20:11.000000Z',
              updated_at: '2021-09-19T21:10:38.000000Z',
              application_id: 6,
              name: 'Incapacidades',
              name_en: null,
              icon: 'fi-rr-ambulance',
              url: 'nomina/disabilities',
              index: 6,
            },
            {
              id: 21,
              created_at: '2021-07-15T12:23:36.000000Z',
              updated_at: '2021-09-19T21:10:38.000000Z',
              application_id: 6,
              name: 'Vacaciones',
              name_en: null,
              icon: 'fi-rr-ping-pong',
              url: 'nomina/vacations',
              index: 4,
            },
            {
              id: 22,
              created_at: '2021-07-15T12:24:55.000000Z',
              updated_at: '2021-09-24T21:35:17.000000Z',
              application_id: 6,
              name: 'Vacaciones (Jefe Área)',
              name_en: null,
              icon: 'fi-rr-ping-pong',
              url: 'nomina/vacationsboss',
              index: 5,
            },
            {
              id: 23,
              created_at: '2021-07-15T12:25:36.000000Z',
              updated_at: '2022-03-09T15:04:59.000000Z',
              application_id: 6,
              name: 'Reporte de Logueo',
              name_en: null,
              icon: 'fi-rr-checkbox',
              url: 'nomina/schedulereport',
              index: 7,
            },
            {
              id: 40,
              created_at: '2021-09-19T21:10:38.000000Z',
              updated_at: '2021-09-19T21:10:38.000000Z',
              application_id: 6,
              name: 'Comisiones',
              name_en: null,
              icon: 'fi-rr-dollar',
              url: 'nomina/commissions',
              index: 8,
            },
            {
              id: 49,
              created_at: '2021-09-19T21:12:44.000000Z',
              updated_at: '2022-03-26T20:08:56.000000Z',
              application_id: 6,
              name: 'Permisos (Jefe Área)',
              name_en: null,
              icon: 'fi-rr-treatment',
              url: 'juridica/permit-boss',
              index: 9,
            },
            {
              id: 97,
              created_at: '2021-12-07T21:00:06.000000Z',
              updated_at: '2022-03-09T15:07:18.000000Z',
              application_id: 6,
              name: 'Reportes',
              name_en: null,
              icon: 'fi-rr-document',
              url: 'nomina/reports',
              index: 9,
            },
            {
              id: 112,
              created_at: '2022-03-07T22:13:19.000000Z',
              updated_at: '2022-03-07T22:13:19.000000Z',
              application_id: 6,
              name: 'jefe Inmediato',
              name_en: null,
              icon: 'fi-rr-user-add',
              url: 'nomina/boss',
              index: 10,
            },
            {
              id: 114,
              created_at: '2022-03-09T15:11:02.000000Z',
              updated_at: '2022-03-09T15:15:23.000000Z',
              application_id: 6,
              name: 'Horas extra',
              name_en: null,
              icon: 'fi-rr-clock',
              url: 'nomina/extrahours/gerencia',
              index: 11,
            },
            {
              id: 115,
              created_at: '2022-03-09T15:13:34.000000Z',
              updated_at: '2022-03-09T15:15:44.000000Z',
              application_id: 6,
              name: 'Horas extra (Jefe inmediato)',
              name_en: null,
              icon: 'fi-rr-clock',
              url: 'nomina/extrahours/boss',
              index: 12,
            },
            {
              id: 125,
              created_at: '2022-04-08T20:42:26.000000Z',
              updated_at: '2022-04-08T20:42:26.000000Z',
              application_id: 6,
              name: 'Asignación de campaña',
              name_en: null,
              icon: 'fi-rr-glasses',
              url: 'nomina/assigncampaign',
              index: 15,
            },
            {
              id: 128,
              created_at: '2022-04-28T15:57:30.000000Z',
              updated_at: '2022-04-28T15:57:30.000000Z',
              application_id: 6,
              name: 'Permisos',
              name_en: null,
              icon: 'fi-rr-treatment',
              url: 'juridica/permit',
              index: 15,
            },
            {
              id: 129,
              created_at: '2022-04-28T16:11:48.000000Z',
              updated_at: '2022-04-28T16:11:48.000000Z',
              application_id: 6,
              name: 'Gestión de retardos',
              name_en: null,
              icon: 'fi-rr-hourglass-end',
              url: 'nomina/aprovationlist',
              index: 16,
            },
            {
              id: 132,
              created_at: '2022-05-03T21:34:19.000000Z',
              updated_at: '2022-05-03T21:34:19.000000Z',
              application_id: 6,
              name: 'asignación de campaña',
              name_en: null,
              icon: 'fi-rr-glasses',
              url: 'nomina/assigncampaign',
              index: 17,
            },
            {
              id: 133,
              created_at: '2022-05-03T21:50:40.000000Z',
              updated_at: '2022-05-03T21:50:40.000000Z',
              application_id: 6,
              name: 'Pasivo vacacional',
              name_en: null,
              icon: 'fi-rr-bowling',
              url: 'nomina/workersvacation',
              index: 18,
            },
            {
              id: 138,
              created_at: '2022-06-13T16:47:16.000000Z',
              updated_at: '2022-06-13T16:47:16.000000Z',
              application_id: 6,
              name: 'Sabado laboral',
              name_en: null,
              icon: 'fi-rr-picture',
              url: 'nomina/saturdayvacations',
              index: 19,
            },
            {
              id: 140,
              created_at: '2022-06-24T14:22:06.000000Z',
              updated_at: '2022-06-24T14:22:06.000000Z',
              application_id: 6,
              name: 'Vacaciones extemporáneas',
              name_en: null,
              icon: 'fi-rr-ping-pong',
              url: 'nomina/vacationsoperations',
              index: 20,
            },
            {
              id: 160,
              created_at: '2022-10-19T14:47:02.000000Z',
              updated_at: '2022-11-16T17:12:32.000000Z',
              application_id: 6,
              name: 'Reporte Referidos',
              name_en: null,
              icon: 'fi-rr-checkbox',
              url: 'nomina/referrals',
              index: 5,
            },
            {
              id: 171,
              created_at: '2022-12-19T15:51:47.000000Z',
              updated_at: '2022-12-19T15:51:47.000000Z',
              application_id: 6,
              name: 'Desprendibles de pagos',
              name_en: null,
              icon: 'fi-rr-document-signed',
              url: 'nomina/import-desprendibles',
              index: 10,
            },
            {
              id: 187,
              created_at: '2022-12-19T15:51:47.000000Z',
              updated_at: '2022-12-19T15:51:47.000000Z',
              application_id: 6,
              name: 'Desprendibles de Liquidaciones',
              name_en: null,
              icon: 'fi-rr-document-signed',
              url: 'nomina/liquidations-import',
              index: 10,
            },
            {
              id: 188,
              created_at: '2023-03-23T14:52:32.000000Z',
              updated_at: '2023-03-23T14:52:32.000000Z',
              application_id: 6,
              name: 'Listado verde',
              name_en: null,
              icon: 'fi-rr-user-time',
              url: 'nomina/import-greenbook',
              index: 30,
            },
            {
              id: 192,
              created_at: '2023-05-26T16:11:14.000000Z',
              updated_at: '2023-05-26T16:11:14.000000Z',
              application_id: 6,
              name: 'Empresas',
              name_en: null,
              icon: 'fi-rr-building',
              url: 'nomina/business',
              index: 9,
            },
          ],
        },
        {
          id: 3,
          name: 'RRHH',
          key: 'rrhh',
          url: '/mios/rrhh',
          enforce_schedule: 0,
          show_menu: 1,
          menu: [
            {
              id: 16,
              created_at: null,
              updated_at: null,
              application_id: 3,
              name: 'Hoja de Vida',
              name_en: null,
              icon: 'fi-rr-document-signed',
              url: 'rrhh/hoja-vida',
              index: 1,
            },
            {
              id: 17,
              created_at: null,
              updated_at: null,
              application_id: 3,
              name: 'Certificados',
              name_en: null,
              icon: 'fi-rr-diploma',
              url: 'rrhh/certificados',
              index: 2,
            },
          ],
        },
        {
          id: 12,
          name: 'Jurídica',
          key: 'juridica',
          url: '/mios/juridica',
          enforce_schedule: 0,
          show_menu: 1,
          menu: [
            {
              id: 42,
              created_at: '2021-09-19T21:12:44.000000Z',
              updated_at: '2023-04-13T16:33:38.000000Z',
              application_id: 12,
              name: 'Mis Recordatorio de Funciones',
              name_en: null,
              icon: 'fi-rr-time-quarter-to',
              url: 'juridica/function-reminder/worker-staff',
              index: 4,
            },
            {
              id: 45,
              created_at: '2021-09-19T21:12:44.000000Z',
              updated_at: '2023-02-10T17:53:15.000000Z',
              application_id: 12,
              name: 'Mis Actas de Descargo',
              name_en: null,
              icon: 'fi-rr-notebook',
              url: 'juridica/certificate/proceedings',
              index: 5,
            },
            {
              id: 68,
              created_at: '2021-10-29T20:37:40.000000Z',
              updated_at: '2021-10-29T20:37:40.000000Z',
              application_id: 12,
              name: 'Mís Otrosíes',
              name_en: null,
              icon: 'fi-rr-document-signed',
              url: 'juridica/otrosi/worker',
              index: 16,
            },
            {
              id: 74,
              created_at: '2021-10-29T20:37:40.000000Z',
              updated_at: '2021-10-29T20:37:40.000000Z',
              application_id: 12,
              name: 'Mís Cesiones',
              name_en: null,
              icon: 'fi-rr-document-signed',
              url: 'juridica/cesion/worker',
              index: 22,
            },
          ],
        },
        {
          id: 14,
          name: 'Club COS',
          key: 'reservas',
          url: '/mios/reservas',
          enforce_schedule: 0,
          show_menu: 1,
          menu: [
            {
              id: 75,
              created_at: '2021-11-02T17:26:11.000000Z',
              updated_at: '2021-11-02T17:26:11.000000Z',
              application_id: 14,
              name: 'Mis Reservas',
              name_en: null,
              icon: 'fi-rr-calendar',
              url: 'reservas/mis-reservas',
              index: 1,
            },
          ],
        },
        {
          id: 2,
          name: 'CRM',
          key: 'crm',
          url: '/mios/crm',
          enforce_schedule: 1,
          show_menu: 1,
          menu: [
            {
              id: 12,
              created_at: null,
              updated_at: null,
              application_id: 2,
              name: 'Grupos',
              name_en: null,
              icon: 'fi-rr-users',
              url: 'crm/groups',
              index: 1,
            },
            {
              id: 13,
              created_at: null,
              updated_at: null,
              application_id: 2,
              name: 'Formularios',
              name_en: null,
              icon: 'fi-rr-form',
              url: 'crm/forms',
              index: 1,
            },
          ],
        },
        {
          id: 5,
          name: 'Escalamientos',
          key: 'pqrs',
          url: '/mios/pqrs',
          enforce_schedule: 0,
          show_menu: 1,
          menu: [],
        },
        {
          id: 29,
          name: 'CRM2',
          key: 'crm2',
          url: '/mios/crm2',
          enforce_schedule: 1,
          show_menu: 1,
          menu: [
            {
              id: 194,
              created_at: '2023-07-19T13:27:15.000000Z',
              updated_at: '2023-07-19T13:27:15.000000Z',
              application_id: 29,
              name: 'Formularios',
              name_en: null,
              icon: 'fi-rr-form',
              url: 'crm2/forms',
              index: 1,
            },
            {
              id: 195,
              created_at: '2023-07-19T13:29:18.000000Z',
              updated_at: '2023-07-19T13:29:18.000000Z',
              application_id: 29,
              name: 'Campañas',
              name_en: null,
              icon: 'fi-rr-folder-add',
              url: 'crm2/campaigns',
              index: 2,
            },
            {
              id: 196,
              created_at: '2023-07-19T13:30:38.000000Z',
              updated_at: '2023-07-19T13:30:38.000000Z',
              application_id: 29,
              name: 'Grupos',
              name_en: null,
              icon: 'fi-rr-users',
              url: 'crm2/groups',
              index: 3,
            },
            {
              id: 197,
              created_at: '2023-07-19T13:32:07.000000Z',
              updated_at: '2023-07-19T13:32:07.000000Z',
              application_id: 29,
              name: 'Gestión Outbound',
              name_en: null,
              icon: 'fi-rr-database',
              url: 'crm2/outbound-manager',
              index: 4,
            },
            {
              id: 198,
              created_at: '2023-07-19T13:33:01.000000Z',
              updated_at: '2023-07-19T13:33:01.000000Z',
              application_id: 29,
              name: 'Circuitos',
              name_en: null,
              icon: 'fi-rr-data-transfer',
              url: 'crm2/circuits',
              index: 5,
            },
            {
              id: 199,
              created_at: '2023-07-19T13:34:08.000000Z',
              updated_at: '2023-07-19T13:34:08.000000Z',
              application_id: 29,
              name: 'Dash Video Call',
              name_en: null,
              icon: 'fi-rr-upload',
              url: 'livechat/omni/dashvideocall',
              index: 6,
            },
            {
              id: 200,
              created_at: '2023-07-19T13:35:44.000000Z',
              updated_at: '2023-07-19T13:35:44.000000Z',
              application_id: 29,
              name: 'Dashboards',
              name_en: null,
              icon: 'fi-rr-grid',
              url: 'crm2/dashboard',
              index: 7,
            },
          ],
        },
        {
          id: 1,
          name: 'CIU',
          key: 'ciu',
          url: '/mios/ciu',
          enforce_schedule: 0,
          show_menu: 1,
          menu: [
            {
              id: 4,
              created_at: null,
              updated_at: null,
              application_id: 1,
              name: 'Grupos',
              name_en: null,
              icon: 'fi-rr-users',
              url: 'ciu/grupos',
              index: 1,
            },
            {
              id: 5,
              created_at: null,
              updated_at: null,
              application_id: 1,
              name: 'Horarios',
              name_en: null,
              icon: 'fi-rr-clock',
              url: 'ciu/horarios',
              index: 1,
            },
            {
              id: 6,
              created_at: null,
              updated_at: null,
              application_id: 1,
              name: 'Usuarios',
              name_en: null,
              icon: 'fi-rr-mode-portrait',
              url: 'ciu/usuarios',
              index: 1,
            },
            {
              id: 7,
              created_at: null,
              updated_at: null,
              application_id: 1,
              name: 'Roles',
              name_en: null,
              icon: 'fi-rr-crown',
              url: 'ciu/roles',
              index: 1,
            },
            {
              id: 8,
              created_at: null,
              updated_at: null,
              application_id: 1,
              name: 'Aplicaciones',
              name_en: null,
              icon: 'fi-rr-apps',
              url: 'ciu/aplicaciones',
              index: 1,
            },
            {
              id: 9,
              created_at: null,
              updated_at: null,
              application_id: 1,
              name: 'Menus',
              name_en: null,
              icon: 'fi-rr-list',
              url: 'ciu/menus',
              index: 1,
            },
            {
              id: 107,
              created_at: '2022-01-25T08:45:29.000000Z',
              updated_at: '2022-02-17T21:32:28.000000Z',
              application_id: 1,
              name: 'Adherencia',
              name_en: null,
              icon: 'fi fi-rr-stats',
              url: 'ciu/adherencia',
              index: 7,
            },
            {
              id: 108,
              created_at: '2022-02-02T16:47:56.000000Z',
              updated_at: '2022-02-17T21:32:42.000000Z',
              application_id: 1,
              name: 'Adherencia',
              name_en: null,
              icon: 'fi-rr-layers',
              url: 'ciu/reportes/1',
              index: 8,
            },
          ],
        },
        {
          id: 34,
          name: 'PQRS SOUL',
          key: 'pqrs_soul',
          url: '/mios/pqrs_soul',
          enforce_schedule: 0,
          show_menu: 1,
          menu: [
            {
              id: 226,
              created_at: '2023-10-20T14:44:15.000000Z',
              updated_at: '2023-10-20T14:44:15.000000Z',
              application_id: 34,
              name: 'inicio',
              name_en: null,
              icon: 'fi-rr-home',
              url: 'pqrs_soul/',
              index: 0,
            },
            {
              id: 228,
              created_at: '2023-10-20T14:45:16.000000Z',
              updated_at: '2023-10-20T14:45:16.000000Z',
              application_id: 34,
              name: 'Gestión PQRS',
              name_en: null,
              icon: 'fi-rr-user-time',
              url: 'pqrs_soul/gestion-pqrs',
              index: 2,
            },
            {
              id: 229,
              created_at: '2023-10-20T14:46:00.000000Z',
              updated_at: '2023-11-01T20:22:48.000000Z',
              application_id: 34,
              name: 'PQRS Externas',
              name_en: null,
              icon: 'fi-rr-users',
              url: 'pqrs_soul/mis-pqrs-externas',
              index: 3,
            },
            {
              id: 230,
              created_at: '2023-10-20T14:46:29.000000Z',
              updated_at: '2023-11-01T20:37:04.000000Z',
              application_id: 34,
              name: 'Reportes',
              name_en: null,
              icon: 'fi-rr-stats',
              url: 'pqrs_soul/reports-pqrs-soul',
              index: 4,
            },
          ],
        },
        {
          id: 35,
          name: 'Encuestas',
          key: 'encuestas',
          url: '/mios/encuestas',
          enforce_schedule: 0,
          show_menu: 1,
          menu: [
            {
              id: 231,
              created_at: '2023-10-26T14:42:46.000000Z',
              updated_at: '2023-10-26T14:42:46.000000Z',
              application_id: 35,
              name: 'Inicio',
              name_en: null,
              icon: 'fi-rr-home',
              url: 'encuestas/',
              index: 1,
            },
            {
              id: 232,
              created_at: '2023-10-26T14:43:57.000000Z',
              updated_at: '2023-10-26T14:43:57.000000Z',
              application_id: 35,
              name: 'Encuestas internas',
              name_en: null,
              icon: 'fi-rr-form',
              url: 'encuestas/lista',
              index: 2,
            },
          ],
        },
        {
          id: 33,
          name: 'Gestor de correos',
          key: 'gestionador-correos',
          url: '/mios/gestionador-correos',
          enforce_schedule: 0,
          show_menu: 1,
          menu: [
            {
              id: 213,
              created_at: '2023-10-17T13:08:20.000000Z',
              updated_at: '2023-10-17T13:08:20.000000Z',
              application_id: 33,
              name: 'Correos',
              name_en: null,
              icon: 'fi-rr-envelope',
              url: 'gestionador-correos/correos',
              index: 1,
            },
            {
              id: 214,
              created_at: '2023-10-17T13:08:45.000000Z',
              updated_at: '2023-10-17T13:08:45.000000Z',
              application_id: 33,
              name: 'Grupo de contactos',
              name_en: null,
              icon: 'fi-sr-users',
              url: 'gestionador-correos/contact-group',
              index: 2,
            },
            {
              id: 215,
              created_at: '2023-10-17T13:09:06.000000Z',
              updated_at: '2023-10-17T13:09:06.000000Z',
              application_id: 33,
              name: 'Categorías',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/categories',
              index: 3,
            },
            {
              id: 216,
              created_at: '2023-10-17T13:09:20.000000Z',
              updated_at: '2023-10-17T13:09:20.000000Z',
              application_id: 33,
              name: 'Estados',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/states',
              index: 4,
            },
            {
              id: 217,
              created_at: '2023-10-17T13:09:40.000000Z',
              updated_at: '2023-10-17T13:09:40.000000Z',
              application_id: 33,
              name: 'Gestión bandejas',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/trays',
              index: 5,
            },
            {
              id: 218,
              created_at: '2023-10-17T13:10:07.000000Z',
              updated_at: '2023-10-17T13:10:07.000000Z',
              application_id: 33,
              name: 'Administración de correos',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/email-config',
              index: 6,
            },
            {
              id: 219,
              created_at: '2023-10-17T13:10:24.000000Z',
              updated_at: '2023-10-17T13:10:24.000000Z',
              application_id: 33,
              name: 'Asignación bandejas',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/assign-trays',
              index: 7,
            },
            {
              id: 220,
              created_at: '2023-10-17T13:10:41.000000Z',
              updated_at: '2023-10-17T13:10:41.000000Z',
              application_id: 33,
              name: 'Asignación correos',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/assign-emails',
              index: 8,
            },
            {
              id: 221,
              created_at: '2023-10-17T13:10:57.000000Z',
              updated_at: '2023-10-17T13:10:57.000000Z',
              application_id: 33,
              name: 'Gestión ANS',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/ans',
              index: 9,
            },
            {
              id: 222,
              created_at: '2023-10-17T13:11:16.000000Z',
              updated_at: '2023-10-17T13:11:16.000000Z',
              application_id: 33,
              name: 'Asignar prioridad',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/assign-priority',
              index: 10,
            },
            {
              id: 223,
              created_at: '2023-10-17T13:11:33.000000Z',
              updated_at: '2023-10-17T13:11:33.000000Z',
              application_id: 33,
              name: 'Reportes',
              name_en: null,
              icon: 'fi-sr-stats',
              url: 'gestionador-correos/supervisor',
              index: 11,
            },
            {
              id: 224,
              created_at: '2023-10-17T13:11:50.000000Z',
              updated_at: '2023-10-17T13:11:50.000000Z',
              application_id: 33,
              name: 'Reasignación de correos',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/email-reassignment',
              index: 12,
            },
            {
              id: 325,
              created_at: '2024-01-23T19:09:30.000000Z',
              updated_at: '2024-01-23T19:09:30.000000Z',
              application_id: 33,
              name: 'Carpetas',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/folders',
              index: 14,
            },
            {
              id: 326,
              created_at: '2024-01-24T18:57:58.000000Z',
              updated_at: '2024-01-24T18:57:58.000000Z',
              application_id: 33,
              name: 'Asignar carpetas',
              name_en: null,
              icon: 'fi-rr-settings\t',
              url: 'gestionador-correos/assign-folders',
              index: 14,
            },
            {
              id: 331,
              created_at: '2024-01-26T19:05:51.000000Z',
              updated_at: '2024-01-26T19:05:51.000000Z',
              application_id: 33,
              name: 'Mover correos',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/move-emails',
              index: 16,
            },
            {
              id: 332,
              created_at: '2024-01-30T20:14:24.000000Z',
              updated_at: '2024-01-30T20:14:24.000000Z',
              application_id: 33,
              name: 'Mover correos cuentas',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/move-emails-account',
              index: 17,
            },
            {
              id: 334,
              created_at: '2024-02-09T19:36:45.000000Z',
              updated_at: '2024-02-09T19:36:45.000000Z',
              application_id: 33,
              name: 'Supervisor v2',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/supervisor-v2',
              index: 18,
            },
            {
              id: 346,
              created_at: '2024-03-01T04:19:16.000000Z',
              updated_at: '2024-03-01T04:19:16.000000Z',
              application_id: 33,
              name: 'Plantillas',
              name_en: null,
              icon: 'fi-rr-settings',
              url: 'gestionador-correos/templates',
              index: 13,
            },
          ],
        },
      ],
      schedule_start: '2024-04-22 01:00:00',
      schedule_extra: {
        scheduleStart: '2024-04-22 01:00:00',
        scheduleEnd: '2024-04-22 23:00:00',
        scheduleEndPlus: '2024-04-23 02:00',
      },
      chat_active: true,
    },
  });
  constructor(private http: HttpClient) {}

  /**
   * UserAuth method is responsible for fetching the authenticated user data.
   * It sends a GET request to the specified API endpoint with the necessary Authorization header.
   *
   * @returns {Observable<any>} - An Observable containing the authenticated user data.
   */
  UserAuth(): Observable<any> {
    const headers = new HttpHeaders({
      Authorization: 'Bearer ' + environment.token,
    });
    return this.http.get(environment.apiUrl + 'user/get-user', { headers });
  }
  

  /**
   * Checks if the user has the required roles to access the chat-interno feature.
   *
   * @param requiredRoles - An array of required roles for accessing the chat-interno feature.
   * @returns A boolean value indicating whether the user has the required roles.
   */
  hasChatInterno(requiredRoles: string[]): boolean {
    const prefix = 'chat-interno::';
    const user = this.jwtDecode.value['user'];
    if (user && user.roles) {
      return requiredRoles.some((requiredRole) =>
        user.roles.includes(`${prefix}${requiredRole}`)
      );
    }
    return false;
  }


  getChatInterno(): string[] {
    const prefix = 'chat-interno::';
    const user = this.jwtDecode.value['user'];
    if (user && user.roles) {
      return user.roles
        .filter(role => role.startsWith(prefix))
        .map(role => role.split('::')[1]);
    }
    return [];
  }

}
